### ISSUE TITLE
INTERNAL SERVER ERROR BUG

### ISSUE THREAD

**Issue by ghost** [Johnmacrocraft/Newspaper#5] opened 2018-12-22 10:02 UTC
### Issue description

It has internal server errors

- Expected result: What were you expecting to happen?
It to be working
- Actual result: What actually happened?
Internal server error

### Steps to reproduce the issue

1. Go make a newspaper
2. Press publish
There you go
Way#2
1.Go to buy/subscribe to the newspaper
There you go again

### OS and versions

* PocketMine-MP: 3.5.1 
* Newspaper:1.0.0
* PHP:??
* Server OS:??
* Game version: PE (delete as appropriate)

### Crashdump, backtrace or other files
```
[Server thread/DEBUG]: #0 Newspaper.phar/src/Johnmacrocraft/Newspaper/forms/PublishItemForm(37): pocketmine\utils\Utils::errorExceptionHandler(integer 8, string Undefined variable: options, string phar:///home/gs/gs/data/servers/11072116/plugins/Newspaper.phar/src/Johnmacrocraft/Newspaper/forms/PublishItemForm.php, integer 37, array Array())
[Server thread/DEBUG]: #1 Newspaper.phar/src/Johnmacrocraft/Newspaper/forms/CreateTypeForm(41): Johnmacrocraft\Newspaper\forms\PublishItemForm->__construct(string INSANEIRON YT, pocketmine\lang\BaseLang object)
[Server thread/DEBUG]: #2 Newspaper.phar/src/Johnmacrocraft/Newspaper/libs/dktapps/pmforms/MenuForm(77): Johnmacrocraft\Newspaper\forms\CreateTypeForm->Johnmacrocraft\Newspaper\forms\{closure}(pocketmine\Player object, integer 1)
[Server thread/DEBUG]: #3 src/pocketmine/Player(3380): Johnmacrocraft\Newspaper\libs\dktapps\pmforms\MenuForm->handleResponse(pocketmine\Player object, integer 1)
[Server thread/DEBUG]: #4 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(249): pocketmine\Player->onFormSubmit(integer 4, integer 1)
[Server thread/DEBUG]: #5 src/pocketmine/network/mcpe/protocol/ModalFormResponsePacket(49): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleModalFormResponse(pocketmine\network\mcpe\protocol\ModalFormResponsePacket object)
[Server thread/DEBUG]: #6 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(99): pocketmine\network\mcpe\protocol\ModalFormResponsePacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
[Server thread/DEBUG]: #7 src/pocketmine/network/mcpe/protocol/BatchPacket(114): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\ModalFormResponsePacket object)
[Server thread/DEBUG]: #8 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(99): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
[Server thread/DEBUG]: #9 src/pocketmine/Player(3044): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
[Server thread/DEBUG]: #10 src/pocketmine/network/mcpe/RakLibInterface(162): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
[Server thread/DEBUG]: #11 vendor/pocketmine/raklib/src/server/ServerHandler(98): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 218.255.247.218 27287, raklib\protocol\EncapsulatedPacket object, integer 0)
[Server thread/DEBUG]: #12 src/pocketmine/network/mcpe/RakLibInterface(102): raklib\server\ServerHandler->handlePacket()
[Server thread/DEBUG]: #13 src/pocketmine/network/Network(94): pocketmine\network\mcpe\RakLibInterface->process()
[Server thread/DEBUG]: #14 src/pocketmine/network/mcpe/RakLibInterface(92): pocketmine\network\Network->processInterface(pocketmine\network\mcpe\RakLibInterface object)
[Server thread/DEBUG]: #15 vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
[Server thread/DEBUG]: #16 vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
[Server thread/DEBUG]: #17 src/pocketmine/Server(2278): pocketmine\snooze\SleeperHandler->sleepUntil(double 1545461136.8121)
[Server thread/DEBUG]: #18 src/pocketmine/Server(2139): pocketmine\Server->tickProcessor()
[Server thread/DEBUG]: #19 src/pocketmine/Server(1715): pocketmine\Server->start()
[Server thread/DEBUG]: #20 src/pocketmine/PocketMine(249): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/gs/gs/data/servers/11072116/, string /home/gs/gs/data/servers/11072116/plugins/)
[Server thread/DEBUG]: #21 /home/gs/gs/data/servers/11072116/PocketMine-MP.phar(1): require(string phar:///home/gs/gs/data/servers/11072116/PocketMine-MP.phar/src/pocketmine/PocketMine.php)
[INFO] INSANEIRON YT left the game
[INFO] INSANEIRON YT[/***.***.***.***:\****\*] logged out due to Internal server error
[NOTICE] Blocked ***.***.***.*** for 5 seconds
[Server thread/DEBUG]: #0 Newspaper.phar/src/Johnmacrocraft/Newspaper/forms/BuyInfoForm(80): Johnmacrocraft\Newspaper\Newspaper->getAllPublished(string server store)
[Server thread/DEBUG]: #1 Newspaper.phar/src/Johnmacrocraft/Newspaper/libs/dktapps/pmforms/MenuForm(77): Johnmacrocraft\Newspaper\forms\BuyInfoForm->Johnmacrocraft\Newspaper\forms\{closure}(pocketmine\Player object, integer 1)
[Server thread/DEBUG]: #2 src/pocketmine/Player(3380): Johnmacrocraft\Newspaper\libs\dktapps\pmforms\MenuForm->handleResponse(pocketmine\Player object, integer 1)
[Server thread/DEBUG]: #3 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(249): pocketmine\Player->onFormSubmit(integer 6, integer 1)
[Server thread/DEBUG]: #4 src/pocketmine/network/mcpe/protocol/ModalFormResponsePacket(49): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleModalFormResponse(pocketmine\network\mcpe\protocol\ModalFormResponsePacket object)
[Server thread/DEBUG]: #5 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(99): pocketmine\network\mcpe\protocol\ModalFormResponsePacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
[Server thread/DEBUG]: #6 src/pocketmine/network/mcpe/protocol/BatchPacket(114): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\ModalFormResponsePacket object)
[Server thread/DEBUG]: #7 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(99): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
[Server thread/DEBUG]: #8 src/pocketmine/Player(3044): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
[Server thread/DEBUG]: #9 src/pocketmine/network/mcpe/RakLibInterface(162): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
[Server thread/DEBUG]: #10 vendor/pocketmine/raklib/src/server/ServerHandler(98): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 218.255.247.218 25621, raklib\protocol\EncapsulatedPacket object, integer 0)
[Server thread/DEBUG]: #11 src/pocketmine/network/mcpe/RakLibInterface(102): raklib\server\ServerHandler->handlePacket()
[Server thread/DEBUG]: #12 src/pocketmine/network/Network(94): pocketmine\network\mcpe\RakLibInterface->process()
[Server thread/DEBUG]: #13 src/pocketmine/network/mcpe/RakLibInterface(92): pocketmine\network\Network->processInterface(pocketmine\network\mcpe\RakLibInterface object)
[Server thread/DEBUG]: #14 vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
[Server thread/DEBUG]: #15 vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
[Server thread/DEBUG]: #16 src/pocketmine/Server(2278): pocketmine\snooze\SleeperHandler->sleepUntil(double 1545461342.2119)
[Server thread/DEBUG]: #17 src/pocketmine/Server(2139): pocketmine\Server->tickProcessor()
[Server thread/DEBUG]: #18 src/pocketmine/Server(1715): pocketmine\Server->start()
[Server thread/DEBUG]: #19 src/pocketmine/PocketMine(249): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/gs/gs/data/servers/11072116/, string /home/gs/gs/data/servers/11072116/plugins/)
[Server thread/DEBUG]: #20 /home/gs/gs/data/servers/11072116/PocketMine-MP.phar(1): require(string phar:///home/gs/gs/data/servers/11072116/PocketMine-MP.phar/src/pocketmine/PocketMine.php)
```

**Comment by Johnmacrocraft** [comment] 2018-12-22 10:20
Duplicate of #4. This bug was fixed on 3d4851c731921ab125d4cf9fab8a92f07826016a, thanks for your report!

**Comment by Johnmacrocraft** [comment] 2018-12-22 10:22
I haven't looked at the way two yet, I'll be investigating this soon.

**Comment by Johnmacrocraft** [comment] 2018-12-22 11:50
~~I can't understand the way two, can you explain in detail?~~

**Closed as completed** 2018-12-22 13:22 UTC
Labels: Type: Bug, Resolution: Fixed

**Comment by Johnmacrocraft** [comment] 2018-12-22 13:27
Fixed in dd5b4b0fa50a22340b9eeb619a8165f57a13b00a. 1.0.1 with these fixes will be released soon on Poggit. You can also download right now from dev builds section!

**Comment by ghost** [comment] 2018-12-22 15:30
The way it works

**Comment by ghost** [comment] 2018-12-24 15:32
Can I find you as my server dev

**Comment by Johnmacrocraft** [comment] 2018-12-25 07:35
@INSANEIRON Unfortunately, I don't have enough time to work as a developer for a server. Sorry!

**Comment by ghost** [comment] 2018-12-25 08:53
I mean we could be finding plugins from elsewhere and make some changes e.g
make enchantments into a shop, and could work slowly and it saves a lot of
time! and also check out my server! IP :InsaneMc.serv.gs Port:40386
We could work out a deal!
