### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SuperAdam47** [Johnmacrocraft/Newspaper#6] opened 2019-01-13 11:55 UTC
### Issue description

```
[Server thread/CRITICAL]: ErrorException: "yaml_emit(): Invalid UTF-8 sequence in argument" (EXCEPTION) in "src/pocketmine/utils/Config" at line 198
```

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### OS and versions
<!--- use the 'version' and 'plugin' command in PocketMine-MP

NOTE: LATEST is not a valid version. PocketMine-MP version should include Jenki

**Comment by Johnmacrocraft** [comment] 2019-01-13 13:52
I don't have enough information to investigate this issue, please send the whole error message and probably your Newspaper data folder.

**Comment by Johnmacrocraft** [comment] 2019-01-13 13:54
Also, you did not put your OS and versions. Please add them to the issue.

**Comment by SuperAdam47** [comment] 2019-01-13 13:55
[Newspaper.zip](https://github.com/Johnmacrocraft/Newspaper/files/2753131/Newspaper.zip)
lastest newspaper version and pmmp api 3.5.5

**Comment by Johnmacrocraft** [comment] 2019-01-13 14:28
@SuperAdam47 What do I exactly have to do to reproduce the issue? Can you explain the step?

**Comment by SuperAdam47** [comment] 2019-01-15 16:08
- /newspaper
- Click buy/read newspapers button
- Click GrandTheftDogs başlangıç

**Comment by Johnmacrocraft** [comment] 2019-01-17 07:49
I'm not able to reproduce the issue on my machine (probably because of encoding). Do you have the full error log (with backtrace)? If so, please post it here.

**Comment by SuperAdam47** [comment] 2019-01-17 18:19
New error 
[21:18:29] [Server thread/CRITICAL]: RuntimeException: "Newspaper not found" (EXCEPTION) in "plugins/Newspaper_dev-35.phar/src/Johnmacrocraft/Newspaper/Newspaper" at line 232

**Comment by SuperAdam47** [comment] 2019-01-17 18:20
I dont removed newspaper data

**Comment by Johnmacrocraft** [comment] 2019-01-23 07:03
Closing since I'm not able to reproduce this on my machine and limited information about the issue. If you want this to be reopened, please post the whole log (with backtrace).

**Closed as completed by Johnmacrocraft** 2019-01-23 07:03 UTC
Labels: Resolution: Cannot reproduce
