### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by ghost** [Johnmacrocraft/Newspaper#8] opened 2019-02-06 15:06 UTC
### Issue description

It is an error when u buy one newspaper

- Expected result: What were you expecting to happen?
It to work
- Actual result: What actually happened?
Internal server error

### Steps to reproduce the issue

1. BUY 1 NEWSPAPER
2. Nothing else

### OS and versions

3.5.8
* PocketMine-MP: 
* Newspaper:
* PHP:
* Server OS:
* Game version: PE (delete as appropriate)

### Crashdump, backtrace or other files
```
[10:02:36] [Server thread/DEBUG]: #0 plugins/Newspaper.phar/src/Johnmacrocraft/Newspaper/forms/BuyItemsListForm(87): Johnmacrocraft\Newspaper\Newspaper->getPublished(string hi, string InsaneMc is good.)
[10:02:36] [Server thread/DEBUG]: #1 plugins/Newspaper.phar/src/Johnmacrocraft/Newspaper/libs/dktapps/pmforms/CustomForm(119): Johnmacrocraft\Newspaper\forms\BuyItemsListForm->Johnmacrocraft\Newspaper\forms\{closure}(pocketmine\Player object, Johnmacrocraft\Newspaper\libs\dktapps\pmforms\CustomFormResponse object)
[10:02:36] [Server thread/DEBUG]: #2 src/pocketmine/Player(3446): Johnmacrocraft\Newspaper\libs\dktapps\pmforms\CustomForm->handleResponse(pocketmine\Player object, array Array())
[10:02:36] [Server thread/DEBUG]: #3 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(258): pocketmine\Player->onFormSubmit(integer 32, array Array())
[10:02:36] [Server thread/DEBUG]: #4 src/pocketmine/network/mcpe/protocol/ModalFormResponsePacket(49): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleModalFormResponse(pocketmine\network\mcpe\protocol\ModalFormResponsePacket object)
[10:02:36] [Server thread/DEBUG]: #5 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(108): pocketmine\network\mcpe\protocol\ModalFormResponsePacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
[10:02:36] [Server thread/DEBUG]: #6 src/pocketmine/network/mcpe/protocol/BatchPacket(119): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\ModalFormResponsePacket object)
[10:02:36] [Server thread/DEBUG]: #7 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(108): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
[10:02:36] [Server thread/DEBUG]: #8 src/pocketmine/Player(3110): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
[10:02:36] [Server thread/DEBUG]: #9 src/pocketmine/network/mcpe/RakLibInterface(170): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
[10:02:36] [Server thread/DEBUG]: #10 vendor/pocketmine/raklib/src/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 223.17.189.195 59391, raklib\protocol\EncapsulatedPacket object, integer 0)
[10:02:36] [Server thread/DEBUG]: #11 src/pocketmine/network/mcpe/RakLibInterface(110): raklib\server\ServerHandler->handlePacket()
[10:02:36] [Server thread/DEBUG]: #12 src/pocketmine/network/mcpe/RakLibInterface(100): pocketmine\network\mcpe\RakLibInterface->process()
[10:02:36] [Server thread/DEBUG]: #13 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
[10:02:36] [Server thread/DEBUG]: #14 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
[10:02:36] [Server thread/DEBUG]: #15 src/pocketmine/Server(2349): pocketmine\snooze\SleeperHandler->sleepUntil(double 1549465356.3244)
[10:02:36] [Server thread/DEBUG]: #16 src/pocketmine/Server(2209): pocketmine\Server->tickProcessor()
[10:02:36] [Server thread/DEBUG]: #17 src/pocketmine/Server(1785): pocketmine\Server->start()
[10:02:36] [Server thread/DEBUG]: #18 src/pocketmine/PocketMine(249): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/gs-40416/, string /home/gs-40416/plugins/)
[10:02:36] [Server thread/DEBUG]: #19 (1): require(string phar:///home/gs-40416/PocketMine-MP.phar/src/pocketmine/PocketMine.php)
[10:02:36] [Server thread/INFO]: Unloading level "is-0.10693100 1547988257"
[10:02:36] [Server thread/INFO]: INSANEIRON YT left the game
[10:02:36] [Server thread/INFO]: INSANEIRON YT[/***.***.***.***:\****\*] logged out due to Internal server error
[10:02:36] [RakLibServer thread/NOTICE]: Blocked ***.***.***.*** for 5 seconds
```

**Comment by ghost** [comment] 2019-02-06 15:08
I’m your bug tester

**Comment by Johnmacrocraft** [comment] 2019-02-11 14:49
I am unable to test this right now because my client crashes when I join the server. Can you download the latest dev build of the plugin and see if it still happens?

**Comment by Johnmacrocraft** [comment] 2019-02-14 15:20
I am unable to reproduce this on the latest dev build, so I'm closing the issue. If you are still able to reproduce it on the latest dev build, please tell me so that I can reopen and fix this.

**Closed as completed by Johnmacrocraft** 2019-02-14 15:20 UTC
Labels: Resolution: Cannot reproduce

**Comment by ghost** [comment] 2019-02-14 15:22
Ok, cheers, just I am hiring a server dev so if u are interested, feel free
and ask :)
